# Site settings
title: Cherry Blossoms
tagline: The Pink Blooms of Spring

url: "" # the base hostname & protocol for your site

# Used for theme in head.html, cannot be used in Stylus files
color-primary: "#4CAF50"

# contact
author:
  name: Paris Fowler
  url: https://github.com/ParisF

twitter_username: ParisF
github_username:  ParisF
github_url: "https://github.com/ParisF/tendaria.xyz"

# Others
markdown: redcarpet

# Exclude Stylus files, nodemodules, and gulpfile
exclude: [node_modules, gulpfile.js, styl, npm-debug.log, Gemfile, Gemfile.lock, LICENSE, README.md, package.json]
